spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true
